-- Usuario/esquema propio de report (no compartir con audit/shipments/catalog).

CREATE TABLE SHIPMENT_EVENT_LOG (
    ID              NUMBER(19)      NOT NULL,
    EVENT_ID        VARCHAR2(100)   NOT NULL,
    SHIPMENT_ID     VARCHAR2(100)   NOT NULL,
    STATUS          VARCHAR2(30)    NOT NULL,
    SERVICE_TYPE    VARCHAR2(100),
    OCCURRED_AT     TIMESTAMP       NOT NULL,
    CONSTRAINT PK_SHIPMENT_EVENT_LOG PRIMARY KEY (ID),
    CONSTRAINT UQ_SHIPMENT_EVENT_ID UNIQUE (EVENT_ID)
);

CREATE SEQUENCE SHIPMENT_EVENT_SEQ START WITH 1 INCREMENT BY 50 NOCACHE;

-- Índices para las agregaciones de KPIs y top-services
CREATE INDEX IX_SHIPMENT_EVENT_STATUS ON SHIPMENT_EVENT_LOG (STATUS, OCCURRED_AT);
CREATE INDEX IX_SHIPMENT_EVENT_SHIPMENT_ID ON SHIPMENT_EVENT_LOG (SHIPMENT_ID);
CREATE INDEX IX_SHIPMENT_EVENT_SERVICE_TYPE ON SHIPMENT_EVENT_LOG (SERVICE_TYPE);
